# fly.toml app configuration file generated for silent-water-2700 on 2023-10-05T21:29:40-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "silent-water-2700"
primary_region = "scl"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
